name: ci-matrix
on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/ci-matrix.yml
    - .github/workflows/scripted-build-matrix-pipeline.yml
    - actions/**
  workflow_dispatch:
    inputs:
      forcePublish:
        description: When true the Publish stage will always be run, otherwise it only runs for tagged versions.
        required: false
        default: false
        type: boolean
      skipCleanup:
        description: When true the pipeline clean-up stage will not be run. For example, the cache used between pipeline stages will be retained.
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write  # enable cache clean-up
  checks: write  # enable test result annotations
  contents: write  # enable creating releases
  issues: read
  packages: write  # enable publishing packages
  pull-requests: write  # enable test result annotations 

jobs:
  prepareConfig:
    name: Prepare Configuration
    runs-on: ubuntu-latest
    outputs:
      RESOLVED_ENV_VARS: ${{ steps.prepareEnvVarsAndSecrets.outputs.environmentVariablesYamlBase64 }}
      RESOLVED_SECRETS: ${{ steps.prepareEnvVarsAndSecrets.outputs.secretsYamlBase64 }}
    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        
    # Declare any environment variables and/or secrets that need to be available inside the build process
    - uses: ./actions/prepare-env-vars-and-secrets
      id: prepareEnvVarsAndSecrets
      with:
        environmentVariablesYaml: |
          BUILDVAR_NuGetPublishSource: "${{ startsWith(github.ref, 'refs/tags/') && 'https://api.nuget.org/v3/index.json' || 'https://nuget.pkg.github.com/endjin/index.json' }}"
        secretsYaml: |
          NUGET_API_KEY: "${{ startsWith(github.ref, 'refs/tags/') && secrets.ENDJIN_NUGET_APIKEY || secrets.ENDJIN_GITHUB_PUBLISHER_PAT }}"
          SBOM_ANALYSIS_RELEASE_READER_PAT: "${{ secrets.ENDJIN_GITHUB_READER_PAT }}"
        secretsEncryptionKey: ${{ secrets.SHARED_WORKFLOW_KEY }}

  build:
    needs: prepareConfig
    uses: ./.github/workflows/scripted-build-matrix-pipeline.yml
    with:
      netSdkVersion: '8.x'
      # workflow_dispatch inputs are always strings, the type property is just for the UI
      forcePublish: ${{ github.event.inputs.forcePublish == 'true' }}
      skipCleanup: ${{ github.event.inputs.skipCleanup == 'true' }}
      publishPhaseEnv: ${{ needs.prepareConfig.outputs.RESOLVED_ENV_VARS }}
      additionalCachePaths: |
        tests
      enableCrossOsCaching: true
      testPhaseMatrixJson: |
        {
          "os": ["ubuntu-latest", "windows-latest"],
          "dotnetFramework": ["net8.0"],
          "exclude": []
        }
    secrets:
      compilePhaseAzureCredentials: ${{ secrets.ENDJIN_PROD_ACR_READER_CREDENTIALS }}
      compilePhaseSecrets: ${{ needs.prepareConfig.outputs.RESOLVED_SECRETS }}
      publishPhaseSecrets: ${{ needs.prepareConfig.outputs.RESOLVED_SECRETS }}
      secretsEncryptionKey: ${{ secrets.SHARED_WORKFLOW_KEY }}
